version: "3.7"
services:
  mysql8:
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${mysql.database}
      MYSQL_ROOT_PASSWORD: ${mysql.pass}
    image: mysql:8
    ports:
      - ${mysql.port}:3306
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: {}
